/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShreveportRouteImport } from './routes/shreveport'
import { Route as NewOrleansRouteImport } from './routes/new-orleans'
import { Route as NatchitochesRouteImport } from './routes/natchitoches'
import { Route as MonroeRouteImport } from './routes/monroe'
import { Route as LouisianaStreetwearRouteImport } from './routes/louisiana-streetwear'
import { Route as LouisianaHumorRouteImport } from './routes/louisiana-humor'
import { Route as LouisianaRouteImport } from './routes/louisiana'
import { Route as LafayetteRouteImport } from './routes/lafayette'
import { Route as HoumaRouteImport } from './routes/houma'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BatonRougeRouteImport } from './routes/baton-rouge'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShreveportRoute = ShreveportRouteImport.update({
  id: '/shreveport',
  path: '/shreveport',
  getParentRoute: () => rootRouteImport,
} as any)
const NewOrleansRoute = NewOrleansRouteImport.update({
  id: '/new-orleans',
  path: '/new-orleans',
  getParentRoute: () => rootRouteImport,
} as any)
const NatchitochesRoute = NatchitochesRouteImport.update({
  id: '/natchitoches',
  path: '/natchitoches',
  getParentRoute: () => rootRouteImport,
} as any)
const MonroeRoute = MonroeRouteImport.update({
  id: '/monroe',
  path: '/monroe',
  getParentRoute: () => rootRouteImport,
} as any)
const LouisianaStreetwearRoute = LouisianaStreetwearRouteImport.update({
  id: '/louisiana-streetwear',
  path: '/louisiana-streetwear',
  getParentRoute: () => rootRouteImport,
} as any)
const LouisianaHumorRoute = LouisianaHumorRouteImport.update({
  id: '/louisiana-humor',
  path: '/louisiana-humor',
  getParentRoute: () => rootRouteImport,
} as any)
const LouisianaRoute = LouisianaRouteImport.update({
  id: '/louisiana',
  path: '/louisiana',
  getParentRoute: () => rootRouteImport,
} as any)
const LafayetteRoute = LafayetteRouteImport.update({
  id: '/lafayette',
  path: '/lafayette',
  getParentRoute: () => rootRouteImport,
} as any)
const HoumaRoute = HoumaRouteImport.update({
  id: '/houma',
  path: '/houma',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BatonRougeRoute = BatonRougeRouteImport.update({
  id: '/baton-rouge',
  path: '/baton-rouge',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/baton-rouge': typeof BatonRougeRoute
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/houma': typeof HoumaRoute
  '/lafayette': typeof LafayetteRoute
  '/louisiana': typeof LouisianaRoute
  '/louisiana-humor': typeof LouisianaHumorRoute
  '/louisiana-streetwear': typeof LouisianaStreetwearRoute
  '/monroe': typeof MonroeRoute
  '/natchitoches': typeof NatchitochesRoute
  '/new-orleans': typeof NewOrleansRoute
  '/shreveport': typeof ShreveportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/baton-rouge': typeof BatonRougeRoute
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/houma': typeof HoumaRoute
  '/lafayette': typeof LafayetteRoute
  '/louisiana': typeof LouisianaRoute
  '/louisiana-humor': typeof LouisianaHumorRoute
  '/louisiana-streetwear': typeof LouisianaStreetwearRoute
  '/monroe': typeof MonroeRoute
  '/natchitoches': typeof NatchitochesRoute
  '/new-orleans': typeof NewOrleansRoute
  '/shreveport': typeof ShreveportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/baton-rouge': typeof BatonRougeRoute
  '/blog': typeof BlogRouteWithChildren
  '/faq': typeof FaqRoute
  '/houma': typeof HoumaRoute
  '/lafayette': typeof LafayetteRoute
  '/louisiana': typeof LouisianaRoute
  '/louisiana-humor': typeof LouisianaHumorRoute
  '/louisiana-streetwear': typeof LouisianaStreetwearRoute
  '/monroe': typeof MonroeRoute
  '/natchitoches': typeof NatchitochesRoute
  '/new-orleans': typeof NewOrleansRoute
  '/shreveport': typeof ShreveportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/baton-rouge'
    | '/blog'
    | '/faq'
    | '/houma'
    | '/lafayette'
    | '/louisiana'
    | '/louisiana-humor'
    | '/louisiana-streetwear'
    | '/monroe'
    | '/natchitoches'
    | '/new-orleans'
    | '/shreveport'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/baton-rouge'
    | '/blog'
    | '/faq'
    | '/houma'
    | '/lafayette'
    | '/louisiana'
    | '/louisiana-humor'
    | '/louisiana-streetwear'
    | '/monroe'
    | '/natchitoches'
    | '/new-orleans'
    | '/shreveport'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/baton-rouge'
    | '/blog'
    | '/faq'
    | '/houma'
    | '/lafayette'
    | '/louisiana'
    | '/louisiana-humor'
    | '/louisiana-streetwear'
    | '/monroe'
    | '/natchitoches'
    | '/new-orleans'
    | '/shreveport'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BatonRougeRoute: typeof BatonRougeRoute
  BlogRoute: typeof BlogRouteWithChildren
  FaqRoute: typeof FaqRoute
  HoumaRoute: typeof HoumaRoute
  LafayetteRoute: typeof LafayetteRoute
  LouisianaRoute: typeof LouisianaRoute
  LouisianaHumorRoute: typeof LouisianaHumorRoute
  LouisianaStreetwearRoute: typeof LouisianaStreetwearRoute
  MonroeRoute: typeof MonroeRoute
  NatchitochesRoute: typeof NatchitochesRoute
  NewOrleansRoute: typeof NewOrleansRoute
  ShreveportRoute: typeof ShreveportRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shreveport': {
      id: '/shreveport'
      path: '/shreveport'
      fullPath: '/shreveport'
      preLoaderRoute: typeof ShreveportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-orleans': {
      id: '/new-orleans'
      path: '/new-orleans'
      fullPath: '/new-orleans'
      preLoaderRoute: typeof NewOrleansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natchitoches': {
      id: '/natchitoches'
      path: '/natchitoches'
      fullPath: '/natchitoches'
      preLoaderRoute: typeof NatchitochesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monroe': {
      id: '/monroe'
      path: '/monroe'
      fullPath: '/monroe'
      preLoaderRoute: typeof MonroeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/louisiana-streetwear': {
      id: '/louisiana-streetwear'
      path: '/louisiana-streetwear'
      fullPath: '/louisiana-streetwear'
      preLoaderRoute: typeof LouisianaStreetwearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/louisiana-humor': {
      id: '/louisiana-humor'
      path: '/louisiana-humor'
      fullPath: '/louisiana-humor'
      preLoaderRoute: typeof LouisianaHumorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/louisiana': {
      id: '/louisiana'
      path: '/louisiana'
      fullPath: '/louisiana'
      preLoaderRoute: typeof LouisianaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lafayette': {
      id: '/lafayette'
      path: '/lafayette'
      fullPath: '/lafayette'
      preLoaderRoute: typeof LafayetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houma': {
      id: '/houma'
      path: '/houma'
      fullPath: '/houma'
      preLoaderRoute: typeof HoumaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baton-rouge': {
      id: '/baton-rouge'
      path: '/baton-rouge'
      fullPath: '/baton-rouge'
      preLoaderRoute: typeof BatonRougeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BatonRougeRoute: BatonRougeRoute,
  BlogRoute: BlogRouteWithChildren,
  FaqRoute: FaqRoute,
  HoumaRoute: HoumaRoute,
  LafayetteRoute: LafayetteRoute,
  LouisianaRoute: LouisianaRoute,
  LouisianaHumorRoute: LouisianaHumorRoute,
  LouisianaStreetwearRoute: LouisianaStreetwearRoute,
  MonroeRoute: MonroeRoute,
  NatchitochesRoute: NatchitochesRoute,
  NewOrleansRoute: NewOrleansRoute,
  ShreveportRoute: ShreveportRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
